version: "3.8"

services:
  city-gen-service:
    build:
      context: ./city-gen-service
      target: development
    volumes:
      - ./city-gen-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
  mongodb:
    image: mongo:latest
    container_name: cityNames
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local