version: "3.8"

services:
  city-gen-service:
    build:
      context: ./city-gen-service
      target: development
    volumes:
      - ./city-gen-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - city-datastore
  city-datastore:
    build: ./city-datastore
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./city-datastore/init.sh:/docker-entrypoint-initdb.d/init.sh
  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
  weather-retriever:
    build:
      context: ./weather-retriever
      target: development
    env_file:
      - weather-retriever/.env
    volumes:
      - ./weather-retriever:/app
    stop_signal: SIGINT
    ports:
      - 4200:4200
    depends_on:
      - redis
      - city-datastore
      - city-gen-service
    environment:
      FLASK_RUN_HOST: 0.0.0.0

volumes:
  mongodata:
    driver: local